# Generated by Django 4.2.7 on 2023-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quantity',
            field=models.IntegerField(default=5, verbose_name='Cantidad'),
        ),
    ]
