# Generated by Django 4.2.7 on 2023-11-24 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost',
            field=models.FloatField(default=100, verbose_name='Costo unitario'),
        ),
    ]
