# Generated by Django 4.2.7 on 2023-11-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(default=500, verbose_name='Costo unitario'),
        ),
    ]
