# Generated by Django 4.2.7 on 2023-12-01 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['created'], 'permissions': [('can_edit_service', 'Puede hacer todo lo del servicio')], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
