# Generated by Django 4.2.7 on 2023-12-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quantity',
            field=models.IntegerField(default=50),
        ),
    ]
